### ISSUE TITLE
Elm Effects don't work without `port tasks`, and you can't debug with them

### ISSUE THREAD

**Issue by seanhess** [evancz/elm-effects#14] opened 2015-08-28 20:16 UTC
I'm working on some animations using elm-effects, but I'm getting an error when I debug. This happens even in the basic example in the tutorial: https://github.com/evancz/elm-architecture-tutorial/tree/master/examples/8

If you clone the repository, run elm-reactor, and debug the example, you get the following error: 

    Cannot read property 'forEach' of undefined

    Open the developer console for more details.

It doesn't crash if you comment out the `port tasks` part in Main.elm, but then the animations don't work. Really debugging my animations is the first time I've really *needed* the debugger. Is there any way to get it work?

**Comment by rgrempel** [comment] 2015-08-28 21:03
I might be wrong, but I think there is a known issue with elm-reactor and ports -- for instance, see

https://github.com/elm-lang/elm-reactor/issues/36

One other way to debug is via the `Debug.log` function -- I've certainly found that handy when working with animations.

**Comment by seanhess** [comment] 2015-08-28 21:31
Excellent thanks! I'll use `Debug.log`

There isn't any way to get elm-effects to work without ports is there? I mean, I'm not using the port for anything, it's more of an implementation detail.

**Comment by rgrempel** [comment] 2015-08-28 22:28
The issue is that elm-effects needs to have some Tasks executed, which requires a port. So, there isn't really any way around it. (That is, as you noticed, without the port statement, the animation doesn't work, because the Tasks that elm-effects uses internally don't get executed).

**Comment by seanhess** [comment] 2015-08-28 23:21
Wait do ports not work with any debugger, or do they not work with elm
reactor? Can I make my own html page to get the debugger working with ports?

**Comment by rgrempel** [comment] 2015-08-29 01:09
Debug.log works fine with ports, to print messages to the console. I'm not sure about other approaches with you own HTML page -- I haven't tried that.

**Comment by rgrempel** [comment] 2015-08-29 21:15
Also, note this Reddit exchange -- looks like ports and elm-reactor don't play nice together at the moment even with your own html page.

https://www.reddit.com/r/elm/comments/3himji/how_to_use_elmreactor_ports_and_custom_html/

**Comment by evancz** [comment] 2015-09-11 00:34
Plan is to have better support for ports + elm-reactor in the future. That is already being tracked elsewhere, so I am going to close this here.

**Closed by evancz** 2015-09-11 00:34 UTC
